name: ELRS Joystick Control (Linux/arm64)
on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  build-binary:
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download builder image
        run: docker pull perfectglitch/linux-arm64-builder
      - name: Build binary
        run: >
          docker run -m 4096m -v ${{ github.workspace }}:/app -t perfectglitch/linux-arm64-builder "
          cd app && 
          ls -la && 
          go generate ./... && 
          go build -trimpath --ldflags '-s -w' -o elrs-joystick-control ./cmd/elrs-joystick-control/.  &&
          go build -trimpath --ldflags '-s -w' -o udp-forwarder ./cmd/udp-forwarder/. &&
          go run scripts/cmd/build-release-zip/build-release-zip.go --location /app --prefix elrs-joystick-control --files elrs-joystick-control,udp-forwarder,LICENSE* "
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: release-linux-arm64
          path: "*.zip"
          retention-days: 5
      - name: Upload zips to GitHub Release
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPLOAD_URL: ${{ github.event.release.upload_url }}
        run: |
          upload_url=${UPLOAD_URL%\{*}
          for f in *.zip; do
            echo "Uploading $f"
            curl -s -X POST \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Content-Type: application/zip" \
              --data-binary @"$f" "$upload_url?name=$(basename "$f")"
          done