name: ELRS Joystick Control (Windows/amd64)
on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  build-binary:
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download builder image
        run: docker pull perfectglitch/windows-amd64-builder
      - name: Build binary
        run: >
          docker run -m 4096m -v ${{ github.workspace }}:C:\app -t perfectglitch/windows-amd64-builder dir /s /c "
          cd app && 
          dir /a && 
          go generate ./... && 
          go build -trimpath -tags static -o elrs-joystick-control.exe .\cmd\elrs-joystick-control\. &&
          go build -trimpath -tags static -o udp-forwarder.exe .\cmd\udp-forwarder\. &&
          go run scripts\cmd\build-release-zip\build-release-zip.go --location C:\app --prefix elrs-joystick-control --files *.exe,LICENSE* "
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: release-windows-amd64
          path: "*.zip"
          retention-days: 5
      - name: Upload zips to GitHub Release
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPLOAD_URL: ${{ github.event.release.upload_url }}
        shell: bash
        run: |
          upload_url=${UPLOAD_URL%\{*}
          for f in *.zip; do
            echo "Uploading $f"
            curl -s -X POST \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Content-Type: application/zip" \
              --data-binary @"$f" "$upload_url?name=$(basename "$f")"
          done